### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by hank2718** [iTaster/webpack4-template#1]
![image](https://user-images.githubusercontent.com/7368299/38975655-3749873e-43e1-11e8-98a7-fc86b9852e56.png)

**Comment by iTaster** [comment]
报错提示是 [name].[contenthash] 这里，我的配置这里已经全部把[contenthash]改为min了，在webpack 4.2之后不再支持ExtractTextPlugin自己的变量[contenthash]，但是[hash]可以
